### ISSUE TITLE
看demo好像是支持美颜的，然而美颜功能并不能用

### ISSUE THREAD

**Issue by TianDehua** [Tencent-RTC/TUILiveKit#1]
是要设置 liscense吗，修改包名，这些最好说明下

**Comment by PualGeorge** [comment]
demo中的美颜模块的“美颜”，“滤镜”这些基础美颜是可以使用的，其他高级美颜功能需要申请linscense，可参考https://cloud.tencent.com/document/product/454/9020，更多问题可加入我们的qq群592465424

**Comment by PualGeorge** [comment]
demo中的美颜模块的“美颜”，“滤镜”这些基础美颜是可以使用的，其他高级美颜功能需要申请linscense，可参考https://cloud.tencent.com/document/product/454/9020 ，更多问题可加入我们的qq群592465424

**Comment by Fay-0768** [comment]
> 

基础美颜功能也并没有全部能用
