### ISSUE TITLE
Android-9.1pk一直显示增在加载中

### ISSUE THREAD

**Issue by GitJoBo** [Tencent-RTC/TUILiveKit#3]
开播后，点击PK，弹框列表没数据，回调【LiveRoomManager.getInstance().getRoomIdList()】也没走，标题一直显示正在加载中...

**Comment by PualGeorge** [comment]
这个是我们这边的业务逻辑问题，稍后跟新仓库代码
如果您急用可TUILiveRoom/Android/App/src/main/java/com/tencent/liteav/demo/MainActivity.java文件的initData()方法中追加下列代码
       `       LiveRoomManager.getInstance().addCallback(new LiveRoomManager.RoomCallback() {
            @Override
            public void onRoomCreate(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().createRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onRoomDestroy(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().destroyRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onGetRoomIdList(final LiveRoomManager.GetCallback callback) {
                RoomManager.getInstance().getRoomIdList(TCConstants.TYPE_LIVE_ROOM, new RoomManager.GetRoomListCallback() {
                    @Override
                    public void onSuccess(List<String> roomIdList) {
                        List<Integer> roomList = new ArrayList<>();
                        for (String id : roomIdList) {
                            try {
                                roomList.add(Integer.parseInt(id));
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                        if (callback != null) {
                            callback.onSuccess(roomList);
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }
        });`

**Comment by PualGeorge** [comment]
这个是我们这边的业务逻辑问题，稍后跟新仓库代码
如果您急用可TUILiveRoom/Android/App/src/main/java/com/tencent/liteav/demo/MainActivity.java文件的initData()方法中追加下列代码
`       LiveRoomManager.getInstance().addCallback(new LiveRoomManager.RoomCallback() {
            @Override
            public void onRoomCreate(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().createRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onRoomDestroy(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().destroyRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onGetRoomIdList(final LiveRoomManager.GetCallback callback) {
                RoomManager.getInstance().getRoomIdList(TCConstants.TYPE_LIVE_ROOM, new RoomManager.GetRoomListCallback() {
                    @Override
                    public void onSuccess(List<String> roomIdList) {
                        List<Integer> roomList = new ArrayList<>();
                        for (String id : roomIdList) {
                            try {
                                roomList.add(Integer.parseInt(id));
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                        if (callback != null) {
                            callback.onSuccess(roomList);
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }
        });`

**Comment by PualGeorge** [comment]
这个是我们demo中没有进行初始化导致的，稍后回跟新仓库代码，您急用的话可以在TUILiveRoom/Android/App/src/main/java/com/tencent/liteav/demo/MainActivity.java文件中的initData()方法中追加下列代码
```
       LiveRoomManager.getInstance().addCallback(new LiveRoomManager.RoomCallback() {
            @Override
            public void onRoomCreate(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().createRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onRoomDestroy(int roomId, final LiveRoomManager.ActionCallback callback) {
                RoomManager.getInstance().destroyRoom(roomId, RoomManager.TYPE_LIVE_ROOM, new RoomManager.ActionCallback() {
                    @Override
                    public void onSuccess() {
                        if (callback != null) {
                            callback.onSuccess();
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }

            @Override
            public void onGetRoomIdList(final LiveRoomManager.GetCallback callback) {
                RoomManager.getInstance().getRoomIdList(TCConstants.TYPE_LIVE_ROOM, new RoomManager.GetRoomListCallback() {
                    @Override
                    public void onSuccess(List<String> roomIdList) {
                        List<Integer> roomList = new ArrayList<>();
                        for (String id : roomIdList) {
                            try {
                                roomList.add(Integer.parseInt(id));
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                        if (callback != null) {
                            callback.onSuccess(roomList);
                        }
                    }

                    @Override
                    public void onFailed(int code, String msg) {
                        if (callback != null) {
                            callback.onError(code, msg);
                        }
                    }
                });
            }
        });
```

**Comment by PualGeorge** [comment]
更多问题可加入我们的qq群592465424

**Comment by PualGeorge** [comment]
这是我们的代码初始化时没有addCallBack导致的，稍后会更新仓库，更多问题可加入我们的qq群592465424

**Comment by GitJoBo** [comment]
更新了吗？邮件发的片段代码部分类接口找不到RoomManager，GetRoomListCallback等，qq群592465424也搜不到

**Comment by PualGeorge** [comment]
您好，目前仓库正在维护中，还没有更新，我已将RoomManager文件在附件中发送给您，请您注意查收。在您修改了MainActivity（和我之前所发内容一致）之后,请在MainActivity同目录下添加RoomManager文件，工程即可正常使用。目前我们的QQ群也已经开启使用QQ号搜索功能，您可加入我们的QQ群，群内每天都有人值班回复，感谢您提出的宝贵意见。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tencentyun/TUILiveRoom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tencentyun/TUILiveRoom] Android-9.1pk一直显示增在加载中 (#3)





 
更新了吗？邮件发的片段代码部分类接口找不到RoomManager，GetRoomListCallback等，qq群592465424也搜不到
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PualGeorge** [comment]
抱歉之前的邮件回复有问题，邮件所发片段代码是使用的示例，在README中也有提到，PK列表需要您使用自己实现的后台服务来获取，我们这边暂不支持提供该服务，需要您自己实现后台，这在README中也有提到，qq群现已实现QQ号搜索，有更多问题可以加入我们的qq群，感谢您的支持！
