### ISSUE TITLE
关于TUIPusher在线观众列表不刷新的问题

### ISSUE THREAD

**Issue by Wananme** [Tencent-RTC/TUILiveKit#5]
主播开始直播，观众进来加群后可以在列表新增显示，但是观众离开（**直接关闭浏览器**），不会触发退群事件，**在线观众列表**不会刷新。
![image](https://user-images.githubusercontent.com/45476748/142832150-f8cb7959-4cee-49de-a5bf-90729ee5cced.png)

查阅API，只有一个统计直播群在线人数的接口和查询账号在线状态的接口。
![image](https://user-images.githubusercontent.com/45476748/142834562-39774043-d6e7-41d7-8eab-e0194045cce1.png)

请问如何在主播端实现实时查看当前直播间具体有哪些人在线呢

**Comment by lixin0** [comment]
在主播端查看当前直播间有哪些用户可以使用TIM的api：

**Comment by lixin0** [comment]
在主播端实现实时查看当前直播间具体有哪些人在线可以使用TIM的接口：https://web.sdk.qcloud.com/im/doc/zh-cn/SDK.html#getGroupMemberList ，使用该接口时注意最多只能获取到直播群前300个在线观众的信息。

TUIPusher中在线观众的处理方式是，主播进房获取直播间的在线观众列表，之后有新的观众进入的时候监听用户进入的消息将新观众添加到在线观众列表中，有观众退出直播间的时候监听退群消息将观众从在线观众列表中移除。这种方式的弊端在于当用户直接关闭浏览器的时候无法执行退群操作，因此主播端无法得知观众已退出直播间。

这里提供更为可靠的方式供您参考，可参考文档 https://cloud.tencent.com/document/product/269/2570#web 配置TIM状态变更回调，在观众直接关闭浏览器的时候会收到状态变更回调并在后台调用 restful api 接口发送自定义消息 https://cloud.tencent.com/document/product/269/1629 通知主播有观众退出直播间。
